#!/bin/bash

## Description: Build the demo website
## Usage: build

# Install Composer dependencies.
composer install --prefer-dist

# Install Drupal from an installation profile.
drush site:install --account-user=admin --account-pass=admin --existing-config --yes
drush cr